### ISSUE TITLE
[Question] IndentedStringBuilder AppendLine(string text) does not add carriage return.

### ISSUE THREAD

**Issue by workgroupengineering** [nventive/Uno.RoslynHelpers#12]
https://github.com/unoplatform/Uno.Roslyn/blob/a1bf3edb594bec39496fa005851b902f4212c462/src/Uno.RoslynHelpers/Content/cs/any/Extensions/IndentedStringBuilder.cs#L89

is it intentional or a error?

**Comment by carldebilly** [comment]
@workgroupengineering Why would you consider this as an error? I'm not sure I understand the problem you're referencing.

**Comment by workgroupengineering** [comment]
Hi @carldebilly ,
When using the AppendLine method, the developer expects a carriage return to be added at the end of the line.
The issue is just a matter of correctly formatting the generated code.

**Comment by carldebilly** [comment]
Good point.

**Comment by davidjohnoliver** [comment]
Agreed that this an unfortunate name for the method - the `Line` suffix does imply a carriage return, by analogy with `Console.WriteLine()` etc.

It would be a big breaking change to modify the behaviour, however, since when generating code (the main use case for `IndentedStringBuilder`) it's often desirable (indeed necessary) to _not_ start a new line before appending further content.
